name: Update ModelScope Badge

on:
  schedule:
    - cron: '0 */3 * * *'  # 每天每隔3小时执行一次（UTC 时间）
  workflow_dispatch:        # 可手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Get CallVolume from ModelScope
        id: fetch
        run: |
          result=$(curl -s -H 'x-modelscope-accept-language: zh_CN' \
            https://www.modelscope.cn/api/v1/mcpServers/Aasee1/open-webSearch)

          raw_value=$(echo "$result" | jq -r '.Data.CallVolume')

          formatted_value=$(echo "$raw_value" | awk '{printf "%.1fk", $1/1000}')

          echo "value=▲ $formatted_value" >> $GITHUB_OUTPUT

      - name: Update Gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          json=$(jq -n --arg v "${{ steps.fetch.outputs.value }}" \
            '{schemaVersion:1,label:"ModelScope",message:$v,color:"orange"}')

          jq -n --arg content "$json" \
            '{files: {"badge.json": {content: $content}}}' > payload.json

          curl -X PATCH "https://api.github.com/gists/${GIST_ID}" \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Content-Type: application/json" \
            --data @payload.json
